project_name: aicli

builds:
  - id: default
    main: ./main.go
    ldflags:
      - "-X github.com/fanook/aicli/cmd.Version={{.Tag}}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - windows
    binary: aicli
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: fanook
    name: aicli
  draft: false
  prerelease: false

changelog:
  use: git
